In [382]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import metrics


In [383]:
bnk_det = pd.read_csv('bank.csv')

In [384]:
bnk_det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [385]:
bnk_det.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [386]:
bnk_det1 = bnk_det.drop(columns=['RowNumber','CustomerId','Surname'],axis=1)
bnk_det1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [387]:
bnk_det1.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

In [388]:
bnk_det1.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [389]:
bnk_det1.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [390]:
bnk_feature_set = bnk_det1.drop(['Geography','Gender'],axis=1)

In [391]:
bnk_target_set = bnk_feature_set.pop('Exited')

In [392]:
bnk_feature_set.head(5)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57  
3               0         93826.63  
4               1         79084.10

In [393]:
X_train, X_test, y_train, y_test = train_test_split(bnk_feature_set, bnk_target_set, test_size=0.3)

In [394]:
print(X_train.shape)
print(y_train.shape)

(7000, 8)
(7000,)


In [395]:
print(X_test.shape)
print(y_test.shape)

(3000, 8)
(3000,)


In [396]:
min_max_scaler = preprocessing.MinMaxScaler()


X_train = min_max_scaler.fit_transform(X_train)

X_test = min_max_scaler.fit_transform(X_test)

In [397]:
print(X_train)

[[0.426      0.18918919 0.6        ... 1.         1.         0.09855191]
 [0.904      0.27027027 0.7        ... 0.         1.         0.28879293]
 [0.47       0.28378378 0.7        ... 1.         0.         0.01194954]
 ...
 [0.446      0.22972973 0.9        ... 1.         1.         0.59962336]
 [0.664      0.43243243 1.         ... 1.         1.         0.51129173]
 [0.748      0.2972973  0.6        ... 1.         1.         0.43473722]]


In [398]:
print(X_test)

[[0.54268293 0.34285714 0.6        ... 1.         0.         0.46697802]
 [0.34756098 0.4        0.8        ... 0.         0.         0.63248672]
 [0.65447154 0.18571429 1.         ... 1.         1.         0.61311411]
 ...
 [0.3597561  0.37142857 0.2        ... 1.         1.         0.68160763]
 [0.30081301 0.45714286 0.3        ... 1.         0.         0.0596692 ]
 [0.43292683 0.24285714 0.8        ... 0.         0.         0.42264747]]


In [399]:
X_train.shape

(7000, 8)

In [400]:
keras.activations.relu(X_test,threshold=0.5)

<tf.Tensor: shape=(3000, 8), dtype=float32, numpy=
array([[0.54268295, 0.        , 0.6       , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.8       , ..., 0.        , 0.        ,
        0.6324867 ],
       [0.6544715 , 0.        , 1.        , ..., 1.        , 1.        ,
        0.6131141 ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.6816076 ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.8       , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)>

In [401]:
model = Sequential()

model.add(Dense(50, activation='relu'))

model.add(Dense(2, activation='softmax', input_shape=(8,)))


In [402]:
sgd = keras.optimizers.SGD(lr = 0.01)

model.compile(optimizer = 'SGD', loss = 'categorical_crossentropy', metrics=['accuracy'])

In [406]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 50)                450       
_________________________________________________________________
dense_14 (Dense)             (None, 2)                 102       
Total params: 552
Trainable params: 552
Non-trainable params: 0
_________________________________________________________________


In [407]:
y_train_bin = keras.utils.to_categorical(y_train)

y_test_bin = keras.utils.to_categorical(y_test)

In [408]:
model.fit(X_train,y_train_bin, epochs = 100)

Epoch 1/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3813 - accuracy: 0.8441
Epoch 2/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3807 - accuracy: 0.8449
Epoch 3/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3800 - accuracy: 0.8447
Epoch 4/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3794 - accuracy: 0.8460
Epoch 5/100
7000/7000 [==============================] - 0s 17us/step - loss: 0.3787 - accuracy: 0.8463
Epoch 6/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3781 - accuracy: 0.8456
Epoch 7/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3775 - accuracy: 0.8471
Epoch 8/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3768 - accuracy: 0.8473
Epoch 9/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3761 - accuracy: 0.8476
Epoch 10/100
7000/7000 [==============================] - 0s 16u

7000/7000 [==============================] - 0s 14us/step - loss: 0.3566 - accuracy: 0.8546
Epoch 80/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3564 - accuracy: 0.8547
Epoch 81/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3564 - accuracy: 0.8560
Epoch 82/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3563 - accuracy: 0.8566
Epoch 83/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3562 - accuracy: 0.8547
Epoch 84/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3561 - accuracy: 0.8539
Epoch 85/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3557 - accuracy: 0.8556
Epoch 86/100
7000/7000 [==============================] - 0s 15us/step - loss: 0.3558 - accuracy: 0.8550
Epoch 87/100
7000/7000 [==============================] - 0s 16us/step - loss: 0.3555 - accuracy: 0.8570
Epoch 88/100
7000/7000 [==============================] - 0s 16us/st

In [409]:
#Accuracy
loss, acc = model.evaluate(X_test_norm, y_test_binary, verbose=0)

print('Accuracy : %.3f' %acc)
print('Loss : %.3f' %loss)

Accuracy : 0.857
Loss : 0.365


In [410]:
y_pred = np.round(model.predict(X_test))
y_pred

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [411]:
y_pred1 = []
for val in y_pred:
    y_pred1.append(np.argmax(val))

In [412]:
#Confusion Matrix

metrics.confusion_matrix(y_test,y_pred1)

array([[2287,  104],
       [ 338,  271]], dtype=int64)