# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0


### Set random seed

In [3]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [5]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.25 ,random_state= 5)
y_train.reshape(-1,1)

array([[0],
       [2],
       [2],
       [1],
       [0],
       [0],
       [1],
       [2],
       [1],
       [2],
       [2],
       [0],
       [2],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [2],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [0],
       [0],
       [2],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [0],
       [0],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [1],
       [2],
       [0],
       [1],
       [0],
       [0],
       [2],
    

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [7]:
from sklearn import preprocessing

In [8]:
enc = preprocessing.OneHotEncoder()

In [9]:
enc.fit(y_train.reshape(-1, 1))


C:\Users\amrit\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [10]:
y_train = enc.transform(y_train.reshape(-1,1)).toarray()

In [11]:
enc.fit(y_test.reshape(-1, 1))

C:\Users\amrit\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [12]:
y_test = enc.transform(y_test.reshape(-1, 1)).toarray()
y_train

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0

## Question 5

### Initialize a sequential model
- Define a sequential model

In [13]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Activation

Using TensorFlow backend.


In [14]:
model1= Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [15]:
model1.add(Dense(3, activation='softmax', input_shape=(4,)))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [16]:
model1.compile(loss='categorical_crossentropy',optimizer='SGD',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [17]:
model1.summary()


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [18]:
history  = model1.fit(x_train, y_train,epochs=100, batch_size=1,validation_data=(x_test, y_test),verbose=1)
print('\nhistory dict:', history.history)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 1ms/step - loss: 1.5233 - accuracy: 0.2321 - val_loss: 0.8862 - val_accuracy: 0.7632
Epoch 2/100
112/112 [==============================] - 0s 570us/step - loss: 0.8223 - accuracy: 0.5982 - val_loss: 0.6822 - val_accuracy: 0.7368
Epoch 3/100
112/112 [==============================] - 0s 579us/step - loss: 0.6329 - accuracy: 0.7679 - val_loss: 0.7729 - val_accuracy: 0.6842
Epoch 4/100
112/112 [==============================] - 0s 588us/step - loss: 0.5736 - accuracy: 0.7589 - val_loss: 0.6731 - val_accuracy: 0.6316
Epoch 5/100
112/112 [==============================] - 0s 597us/step - loss: 0.5204 - accuracy: 0.7500 - val_loss: 0.5811 - val_accuracy: 0.6316
Epoch 6/100
112/112 [==============================] - 0s 596us/step - loss: 0.4715 - accuracy: 0.7768 - val_loss: 0.5661 - val_accuracy: 0.6842
Epoch 7/100
112/112 [==============================] - 0s 552us/step - loss: 0.4615 - a

Epoch 57/100
112/112 [==============================] - 0s 559us/step - loss: 0.1597 - accuracy: 0.9732 - val_loss: 0.2014 - val_accuracy: 0.8947
Epoch 58/100
112/112 [==============================] - 0s 552us/step - loss: 0.1461 - accuracy: 0.9821 - val_loss: 0.2504 - val_accuracy: 0.8684
Epoch 59/100
112/112 [==============================] - 0s 570us/step - loss: 0.1510 - accuracy: 0.9643 - val_loss: 0.2802 - val_accuracy: 0.8684
Epoch 60/100
112/112 [==============================] - 0s 552us/step - loss: 0.1445 - accuracy: 0.9643 - val_loss: 0.2098 - val_accuracy: 0.8947
Epoch 61/100
112/112 [==============================] - 0s 543us/step - loss: 0.1528 - accuracy: 0.9821 - val_loss: 0.2153 - val_accuracy: 0.8947
Epoch 62/100
112/112 [==============================] - 0s 550us/step - loss: 0.1442 - accuracy: 0.9911 - val_loss: 0.1869 - val_accuracy: 0.9211
Epoch 63/100
112/112 [==============================] - 0s 570us/step - loss: 0.1490 - accuracy: 0.9732 - val_loss: 0.1863 -

In [19]:
loss, acc = model1.evaluate(x_test, y_test, verbose=0)
print('Accuracy: %.3f'  % acc)
print('Loss: %.3f' % loss)

Accuracy: 0.895
Loss: 0.178


## Question 10

### Make predictions
- Predict labels on one row

In [27]:
y_premod = model1.predict(x_test)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [28]:
print("Predicted one",y_premod[0:4])
print("Actual one",y_test[0:4])

Predicted one [[1.5037649e-02 9.6668142e-01 1.8280946e-02]
 [3.1373671e-05 1.3734420e-01 8.6262435e-01]
 [4.2489896e-06 6.3483980e-03 9.9364728e-01]
 [9.8745000e-01 1.2550049e-02 2.5074602e-08]]
Actual one [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [0]:
import tensorflow as tf
print(tf.__version__)

### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

### Observe values of Weight
- Print the updated values

### Observe values of Bias
- Print the updated values