### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [35]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.__version__)

2.1.0


#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
(x_train, y_train),(x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

#### Change train and test labels into one-hot vectors

In [37]:
print("X train shape:",x_train.shape)
print("Y train shape:",y_train.shape)
print("X test shape:",x_test.shape)
print("Y test shape:",y_test.shape)

X train shape: (60000, 28, 28)
Y train shape: (60000,)
X test shape: (10000, 28, 28)
Y test shape: (10000,)


In [38]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [39]:
y_test

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes = 10)
y_test = tf.keras.utils.to_categorical(y_test, num_classes = 10)

In [41]:
print(y_train)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [42]:
print(ytest)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
x_train = x_train.astype('float32')      
x_test = x_test.astype('float32')
x_train /= 255                           
x_test /= 255

In [44]:
x_train = x_train.reshape(60000, 28,28,1)    
x_test = x_test.reshape(10000, 28,28,1)      
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [0]:
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.activations import relu
from tensorflow.keras.layers import Convolution2D, MaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
model = Sequential()


model.add(tf.keras.layers.Conv2D(32,kernel_size=(3,3), #Size of the filter
                                 activation='relu',input_shape=(28,28,1,)))
model.add(tf.keras.layers.Conv2D(32,kernel_size=(3,3), #Size of the filter
                                 activation='relu'))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))



### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [47]:
model.add(tf.keras.layers.Dense(10, activation='softmax'))



model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

es = EarlyStopping(monitor='val_loss', mode='min', patience=5, verbose=1) 

model.fit(x_train, y_train,          
          validation_data=(x_test, y_test),
          epochs=10,
          callbacks = [es])

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 18s 305us/sample - loss: 0.4217 - accuracy: 0.8486 - val_loss: 0.3175 - val_accuracy: 0.8874
Epoch 2/10
60000/60000 [==============================] - 17s 289us/sample - loss: 0.2583 - accuracy: 0.9050 - val_loss: 0.2628 - val_accuracy: 0.9073
Epoch 3/10
60000/60000 [==============================] - 18s 292us/sample - loss: 0.1967 - accuracy: 0.9270 - val_loss: 0.2527 - val_accuracy: 0.9134
Epoch 4/10
60000/60000 [==============================] - 17s 288us/sample - loss: 0.1466 - accuracy: 0.9456 - val_loss: 0.2816 - val_accuracy: 0.9058
Epoch 5/10
60000/60000 [==============================] - 17s 290us/sample - loss: 0.1043 - accuracy: 0.9610 - val_loss: 0.3073 - val_accuracy: 0.9089
Epoch 6/10
60000/60000 [==============================] - 17s 282us/sample - loss: 0.0765 - accuracy: 0.9713 - val_loss: 0.3519 - val_accuracy: 0.9049
Epoch 7/10
60000/60000 [====================

In [48]:
es = EarlyStopping(monitor='val_loss', mode='min', patience=5, verbose=1) 

history = model.fit(x_train, y_train,epochs=10,verbose=1,validation_data=(x_test, y_test),callbacks = [es])

score = model.evaluate(x_test, y_test, verbose=False)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 18s 301us/sample - loss: 0.0360 - accuracy: 0.9877 - val_loss: 0.4618 - val_accuracy: 0.9116
Epoch 2/10
60000/60000 [==============================] - 18s 297us/sample - loss: 0.0294 - accuracy: 0.9897 - val_loss: 0.5114 - val_accuracy: 0.9140
Epoch 3/10
60000/60000 [==============================] - 18s 301us/sample - loss: 0.0271 - accuracy: 0.9904 - val_loss: 0.5434 - val_accuracy: 0.9097
Epoch 4/10
60000/60000 [==============================] - 18s 303us/sample - loss: 0.0248 - accuracy: 0.9917 - val_loss: 0.5714 - val_accuracy: 0.9091
Epoch 5/10
60000/60000 [==============================] - 18s 301us/sample - loss: 0.0193 - accuracy: 0.9931 - val_loss: 0.6820 - val_accuracy: 0.9030
Epoch 6/10
60000/60000 [==============================] - 18s 298us/sample - loss: 0.0225 - accuracy: 0.9929 - val_loss: 0.5946 - val_accuracy: 0.9122
Epoch 00006: early stopping


In [0]:
import matplotlib.pyplot as plt

In [54]:

loss,accuracy  = model.evaluate(x_test, y_test, verbose=False)
print("model accuracy :" , accuracy)
#print("validation accuracy : ", val_accuracy)


model accuracy : 0.9122


In [55]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 24, 24, 32)        9248      
_________________________________________________________________
flatten_2 (Flatten)          (None, 18432)             0         
_________________________________________________________________
dense_6 (Dense)              (None, 200)               3686600   
_________________________________________________________________
dense_7 (Dense)              (None, 100)               20100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)               